### ISSUE TITLE
cargo metadata fields are missing

### ISSUE THREAD

**Issue by mainrs** [sergey-melnychuk/rust-parser-combinators#5]
repository, homepage (if needed) and readme

**Comment by mainrs** [comment]
You sure you released the right crate? :D Looks more like http related stuff than parser combinators 🤔

**Comment by sergey-melnychuk** [comment]
Thanks, will add those fields in just few minutes. 

Yes, parser combinators - with a few provided simple parsers for HTTP request and WebSocket frame.

**Comment by mainrs** [comment]
> Yes, parser combinators - with a few provided simple parsers for HTTP request and WebSocket frame.

Ah got you! Looking forward, sounds super interesting :)

**Comment by sergey-melnychuk** [comment]
Fixed
